name: json_schema
version: 1.0.8

authors:
  - Michael Carter <michael.carter@workiva.com>
  - Daniel Davidson <dbdavidson@yahoo.com>
  
homepage: https://github.com/workiva/json_schema
description: >
  Provide support for validating instances against json schema
environment:
  sdk: ">=1.8.2 <2.0.0"

dependencies:
  args: ">=0.11.0 <2.0.0"
  logging: ">=0.9.3<0.12.0"
  path: "^1.3.0"

dev_dependencies:
  coverage: ">=0.7.6"
  dart_dev: any
  dart_style: any
  dependency_validator: ^1.0.0
  test: "^0.12.13"
