name: json_schema
version: 2.0.1
description: Provide support for validating instances against json schema
authors:
  - Michael Carter <michael.carter@workiva.com>
  - Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/workiva/json_schema

environment:
  sdk: ">=1.24.3 <3.0.0"

dependencies:
  args: ">=0.13.7 <2.0.0"
  dart2_constant: ^1.0.0
  logging: ">=0.9.3 <0.12.0"
  path: ^1.3.0
  uri: ">=0.11.1 <0.12.0"
  w_transport: ^3.2.8

dev_dependencies:
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ">=0.9.0 <2.0.0"
  build_web_compilers: ">=0.2.0 <2.0.0"
  coverage: ">=0.10.0 <0.13.0"
  dart_dev: ^2.0.0
  dart_style: ^1.0.9
  dependency_validator: ^1.2.1
  shelf: ^0.7.2
  shelf_static: ^0.2.7
  test: ">=0.12.30 <2.0.0"
