name: json_schema
version: 2.0.0-RC1RC1

authors:
  - Michael Carter <michael.carter@workiva.com>
  - Daniel Davidson <dbdavidson@yahoo.com>
  
homepage: https://github.com/workiva/json_schema
description: >
  Provide support for validating instances against json schema
environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:
  args: '>=0.11.0 <2.0.0'
  logging: '>=0.9.3<0.12.0'
  path: '^1.3.0'
  uri_template: ^0.6.0
  w_transport: ^3.1.2

dev_dependencies:
  coverage: '>=0.7.6'
  dart_dev: any
  dart_style: any
  dependency_validator: ^1.0.0
  shelf: ^0.7.2
  shelf_static: ^0.2.7
  test: '^0.12.13'
